services:
  - type: web
    name: food-castle-api
    env: python
    buildCommand: pip install uv && uv pip install --system .
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_1_USERNAME
        sync: false
      - key: ADMIN_1_PASSWORD
        sync: false
      - key: ADMIN_2_USERNAME
        sync: false
      - key: ADMIN_2_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: food-castle-db
          property: connectionString

databases:
  - name: food-castle-db
    databaseName: food_castle
    user: food_castle_user
